### ISSUE TITLE
Rotate button does not work on Mac OS

### ISSUE THREAD

**Issue by ingo-m** [ofgulban/segmentator#55]
On Mac, the `Rotate` button does not work.

Tested with following system/environment configuration:

| Package    | Version |
|------------|---------|
| Mac OS     | 10.12.6.|
| numpy      |  1.11.3 |
| scipy      |  0.19.0 |
| matplotlib |   2.0.2 |
| nibabel    |   2.1.0 |

This is the output after loading an nii image and clicking the `Rotate` button:

```bash
segmentator mp2rage_t1w.nii
=================
Segmentator 1.3.0
=================
Traceback (most recent call last):
  File "/Users/john/miniconda2/envs/py_main/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 1940, in button_release_event
    self.callbacks.process(s, event)
  File "/Users/john/miniconda2/envs/py_main/lib/python2.7/site-packages/matplotlib/cbook.py", line 554, in process
    proxy(*args, **kwargs)
  File "/Users/john/miniconda2/envs/py_main/lib/python2.7/site-packages/matplotlib/cbook.py", line 416, in __call__
    return mtd(*args, **kwargs)
  File "/Users/john/miniconda2/envs/py_main/lib/python2.7/site-packages/matplotlib/widgets.py", line 229, in _release
    func(event)
  File "build/bdist.macosx-10.6-x86_64/egg/segmentator/gui_utils.py", line 359, in changeRotation
  File "build/bdist.macosx-10.6-x86_64/egg/segmentator/gui_utils.py", line 352, in rotateIma90
TypeError: rot90() got an unexpected keyword argument 'axes'
```

**Comment by ofgulban** [comment]
This error comes up because you have used an outdated numpy version.

**Comment by ingo-m** [comment]
Yes I can confirm this, after updating to numpy version 1.13.3 the problem does not occur any more.
