### ISSUE TITLE
Can't make new version run

### ISSUE THREAD

**Issue by katjaq** [ofgulban/segmentator#76]
Hello,

I was very happy using segmentator \ö/ great tool! However, I cannot seem to get the new version running.
I synced on the master branch, and followed the instructions in your ReadMe. All console logs seem happy, however, when trying to run segmentator, I get the following error:
```ModuleNotFoundError: No module named 'segmentator.deriche_3D'
```
my complete console log:
=================
Segmentator 1.5.2
=================
Default GUI is selected.
/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/anaconda3/bin/segmentator", line 11, in <module>
    load_entry_point('segmentator==1.5.2', 'console_scripts', 'segmentator')()
  File "/Users/katja/code/segmentator/segmentator/__main__.py", line 173, in main
    import segmentator.segmentator_main
  File "/Users/katja/code/segmentator/segmentator/segmentator_main.py", line 31, in <module>
    from segmentator.utils import map_ima_to_2D_hist, prep_2D_hist
  File "/Users/katja/code/segmentator/segmentator/utils.py", line 28, in <module>
    from segmentator.deriche_prepare import Deriche_Gradient_Magnitude
  File "/Users/katja/code/segmentator/segmentator/deriche_prepare.py", line 22, in <module>
    from segmentator.deriche_3D import deriche_3D
ModuleNotFoundError: No module named 'segmentator.deriche_3D'

my system: 
Mac OS High Sierra Version 10.13.5 (17F77)

Many thanks in advance for your help.

Best
katja

**Comment by ingo-m** [comment]
@katjaq I think this is related to python 3.6. I just installed the latest version of segmentator (from branch master) on a macOS with High Sierra Version 10.13.5 in Python 2.7, and it works fine. Could you try in python 2.7? (I.e. create a conda environment with `conda create -n segmentator_env pip numpy scipy python=2.7`, followed by the regular installation steps, i.e. `pip install -r requirements.txt` and `python setup.py install`)?

**Comment by ingo-m** [comment]
I was wrong, it's not a python 3.6 issue, I just tried to reproduce the problem under Python 3.6.5 on mac (High Sierra Version 10.13.5) but the problem does not occur.

I suggest that you open a new terminal and try open segmentator (`segmentator /path/to/file.nii.gz`). If that still does not work, do `which segmentator` and post the output here. 

(The path `/Users/katja/code/segmentator/segmentator/main.py` suggests that you are not calling the installed version of segmentator, but the segmentator function in your clone of the github repository.)

**Comment by katjaq** [comment]
Heyy! Thank you so much, dear Ingo. That was it :D 
```which segmentator``` was pointing to the right one
```/anaconda3/bin/segmentator``` – I needed to open a new terminal window after installation. I am sorry I didn't have this idea.

Many thanks for your fast feedback! It is all running fine now :)

Best wishes
katja

**Comment by ofgulban** [comment]
Dear @katjaq and @ingo-m , 
Thanks a lot for the report and the fast solution :).
I have now put a workaround (in `devel` branch) that should prevent this from happening in the future.

**Comment by katjaq** [comment]
:D you guys are fantastic!!
many thanks again!
